### ISSUE TITLE
404 for all nightlies except the most recent nightly

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/murdock-scripts#21]
If I go to https://ci.riot-os.org/nightlies.html#master and click on any build except the most recent build I get a 404 error.

**Comment by smlng** [comment]
that's because we have only limited disk space on the the CI-Master node, which is why we regularly backup *historic* build results to another storage server and delete them on the master. I will limit this to PR builds in the future and preserve nightlies so they remain reachable.

Sorry for the *inconvenience* 😉

**Comment by miri64** [comment]
Thanks for the clarification. Weird though to have limited disk space on a CI-Master node :-/.

**Comment by tcschmidt** [comment]
Yep, we will change this ASAP

**Comment by smlng** [comment]
I restored all previous nightly builds from backup, all links should work now - no more 404.
